import os.path
project = 'tests'

Import('env', 'build_mode', 'debugcflags', 'releasecflags', 'covcflags')
localenv = env.Clone()

pg_src = Glob('*.c')

if build_mode == 'debug':
    localenv.Append(CCFLAGS=debugcflags)
elif build_mode == 'cov':
    localenv.Append(CCFLAGS=covcflags)
else:
    localenv.Append(CCFLAGS=releaseflags)

_tests = Glob('*.c')

e = localenv.Clone(LIBS = ['perf-gear', 'duktape', 'm' , 'pthread', 'curl', 'cunit'], CPPPATH = ['../lib'])
for test in _tests:
    # _targetpath = '/' + os.path.splitext(test.rstr())[0]
    # print _targetpath
    e.Program(test)
