import os.path
project = 'tests'

Import('env', 'build_mode', 'debugcflags', 'releasecflags', 'covcflags')
localenv = env.Clone()

buildroot = '../' + build_mode
builddir = buildroot + '/' + project

pg_src = Glob('*.c')

if build_mode == 'debug':
    localenv.Append(CCFLAGS=debugcflags)
elif build_mode == 'cov':
    localenv.Append(CCFLAGS=covcflags)
else:
    localenv.Append(CCFLAGS=releaseflags)

_tests = Glob('*.c')

e = localenv.Clone(LIBS = ['perf-gear', 'duktape', 'm' , 'pthread', 'cunit'])
for test in _tests:
    targetpath = builddir + '/' + os.path.splitext(test.rstr())[0]
    print targetpath
    e.Program(targetpath, test)
