project = 'js-tests'

Import('env', 'build_mode', 'debugcflags', 'releasecflags', 'covcflags')
localenv = env.Clone()

buildroot = '../build/' + build_mode
targetpath = buildroot + '/' + project

if build_mode == 'debug':
    localenv.Append(CCFLAGS=debugcflags)
elif build_mode == 'cov':
    localenv.Append(CCFLAGS=covcflags)
else:
    localenv.Append(CCFLAGS=releaseflags)



js_test_1 = 'js-runner.c'

e = localenv.Clone(LIBS = ['perf-gear', 'duktape', 'm' , 'pthread', 'curl'], CPPPATH = ['../lib'])
e.Program(js_test_1)

_tests = Glob('*.js')
for test in _tests:
	Command('../'+project+'/'+test.get_path(), test.rstr(), Copy("$TARGET", "$SOURCE"))