project = 'js-tests'

Import('env', 'build_mode', 'debugcflags', 'releasecflags', 'covcflags')
localenv = env.Clone()

buildroot = '../' + build_mode
builddir = buildroot + '/' + project
targetpath = builddir

if build_mode == 'debug':
    localenv.Append(CCFLAGS=debugcflags)
elif build_mode == 'cov':
    localenv.Append(CCFLAGS=covcflags)
else:
    localenv.Append(CCFLAGS=releaseflags)


js_test_1 = 'js-runner.c'

e = localenv.Clone(LIBS = ['perf-gear', 'duktape', 'm' , 'pthread'])
e.Program(targetpath+'/js-runner', js_test_1)
