project = 'perf-gear'

Import('env', 'build_mode', 'debugcflags', 'releasecflags', 'covcflags')
localenv = env.Clone()

pg_src = Glob('*.c')

if build_mode == 'debug':
    localenv.Append(CCFLAGS=debugcflags)
elif build_mode == 'cov':
    localenv.Append(CCFLAGS=covcflags)
else:
    localenv.Append(CCFLAGS=releaseflags)

localenv.Library(project, pg_src)
