project = 'perf-gear'

Import('env', 'build_mode', 'debugcflags', 'releasecflags', 'covcflags')
localenv = env.Copy()

buildroot = '../' + build_mode
builddir = buildroot + '/' + project
targetpath = builddir + '/' + project

pg_src = Glob('*.c')

if build_mode == 'debug':
    localenv.Append(CCFLAGS=debugcflags)
elif build_mode == 'cov':
    localenv.Append(CCFLAGS=covcflags)
else:
    localenv.Append(CCFLAGS=releaseflags)

env.Library('perf-gear', pg_src)
